
spring.datasource.url=mysql://root:YRaaRVhSGeasosLfkIOyYxyjbHtrxMKR@thomas.proxy.rlwy.net:13266/railway
spring.datasource.username=root
spring.datasource.password=YRaaRVhSGeasosLfkIOyYxyjbHtrxMKR

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


jwt.expiration=86400000

server.port=${PORT:8080}

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

